version: '2.0'
services:
  flick-cost:
    container_name: flick-cost
    image: docker.tonoli.io:5000/flick-cost:1.0.0
    env_file:
      - /etc/environment
    environment:
      - NODE_ENV=flick
    volumes:
      - /opt/flick-cost/config:/opt/flick-cost/config/


